### PR TITLE
[DRAFT] Compute@Edge compatibility

### PR DESCRIPTION
**Pull request by doramatadora**

### CODE REVIEW

**Comment by jedisct1** [comment]
Hi Dora!

And thank you! Using `libwasi-emulated-getpid` is a good idea!

**Comment by jedisct1** [comment]
This is failing with:

```
crypto/asn1/a_time.c:599:10: error: 'USE_TIMEGM' macro redefined [-Werror,-Wmacro-redefined]
# define USE_TIMEGM
         ^
<command line>:10:9: note: previous definition is here
#define USE_TIMEGM 1
        ^
1 error generated.
make[1]: *** [crypto/asn1/libcrypto-lib-a_time.o] Error 1
```

So I guess we need to remove this?

**Comment by jedisct1** [comment]
We also need to define `SIXTY_FOUR_BIT`.  That can probably be done by adding a configuration for WebAssembly in the `Configurations` directory.

**Comment by jedisct1** [comment]
In fact we can probably put everything wasi-specific in `Configurations`.

**Comment by IgorKhomenko** [comment]
@jedisct1 were you able to compile it ?

**Pull request closed without merging**
